apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  labels:
    app: myspringbootapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myspringbootapp
  template:
    metadata:
      labels:
        app: myspringbootapp
    spec:
      containers:
      - name: myspringbootapp
        image: my-app-image:latest
        ports:
        - containerPort: 80
        env:
        - name: ENV_VAR_NAME
          value: "example-value"
